name: Builds, tests & co

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout tree
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@f92e0606b7ae4873dd1238465ea4bf6f8e40d85c # v3.7.2
        with:
          ocaml-compiler: 5
      - run: opam install . --deps-only
      - run: opam exec -- dune build

  lint-fmt:
    name: Lint fmt
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout tree
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@f92e0606b7ae4873dd1238465ea4bf6f8e40d85c # v3.7.2
        with:
          ocaml-compiler: 5
      - uses: ocaml/setup-ocaml/lint-fmt@f92e0606b7ae4873dd1238465ea4bf6f8e40d85c # v3.7.2

  lint-opam:
    name: Lint opam
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout tree
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@f92e0606b7ae4873dd1238465ea4bf6f8e40d85c # v3.7.2
        with:
          ocaml-compiler: 5
      - uses: ocaml/setup-ocaml/lint-opam@f92e0606b7ae4873dd1238465ea4bf6f8e40d85c # v3.7.2

  lint-taplo:
    name: Lint taplo
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout tree
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set-up Homebrew
        uses: Homebrew/actions/setup-homebrew@3cdb78d0f62ad29dd32de765782654f4eedea607 # 2026.08.31.1
      - run: brew install taplo
      - run: taplo lint
