name: Opam Dependency Submission

on:
  push:
    branches:
      - main

concurrency:
  group: opam-dependency-submission
  cancel-in-progress: true

permissions: {}

jobs:
  opam-dependency-submission:
    name: Opam Dependency Submission
    permissions:
      contents: write # needed to submit dependency graph snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@f92e0606b7ae4873dd1238465ea4bf6f8e40d85c # v3.7.2
        with:
          ocaml-compiler: 5
      - uses: ocaml/setup-ocaml/analysis@f92e0606b7ae4873dd1238465ea4bf6f8e40d85c # v3.7.2
